import { TOWER_TYPES } from '../data/towers.js';

let nextId = 0;

export function createTower(type, x, y) {
  const def = TOWER_TYPES[type];
  return {
    id: ++nextId,
    type, x, y,
    targeting: 'first',
    cooldown: 0,
    damage:       def.damage,
    range:        def.range,
    fireRate:     def.fireRate,
    projSpeed:    def.projSpeed,
    aoeRadius:    def.aoeRadius   ?? 0,
    isSlow:       def.isSlow      ?? false,
    slowFactor:   def.slowFactor  ?? 0,
    slowDuration: def.slowDuration ?? 0,
    isStun:       def.isStun      ?? false,
    stunDuration: def.stunDuration ?? 0,
    globalRange:  def.globalRange  ?? false,
    isEconomy:    def.isEconomy    ?? false,
    pierce:       def.pierce       ?? 0,
    dotDamage:        def.dotDamage        ?? 0,
    dotDuration:      def.dotDuration      ?? 0,
    dotTickRate:      def.dotTickRate      ?? 1.0,
    dotIgnoresArmour: def.dotIgnoresArmour ?? false,
    dotStackCap:      def.dotStackCap      ?? 1,
    incomePerWave:      def.incomePerWave      ?? 0,
    killCashBoostRange: def.killCashBoostRange ?? 0,
    killCashBoostMult:  def.killCashBoostMult  ?? 0,
    leavesHazard:   def.leavesHazard   ?? false,
    hazardDamage:   def.hazardDamage   ?? 0,
    hazardRadius:   def.hazardRadius   ?? 30,
    hazardDuration: def.hazardDuration ?? 4.0,
    hazardTickRate: def.hazardTickRate ?? 0.5,
    upgradesA:    0,
    upgradesB:    0,
    upgradeSpent: 0,
    angle:        0, // radians — updated by CombatSystem; used by TowerRenderer for barrel direction
    multiShot:    def.multiShot   ?? 1,
    isSupport:    def.isSupport   ?? false,
    buffFireRate: def.buffFireRate ?? 0,
    buffDamage:   def.buffDamage   ?? 0,
    buffRange:    def.buffRange    ?? 0,
    camoDetect:   def.camoDetect   ?? false,
    buffedFireRate: 0,
    buffedDamage:   0,
    buffedRange:    0,
    camoVisible:    false,
    debuffVulnerability: def.debuffVulnerability ?? 0,
    debuffDuration:      def.debuffDuration      ?? 0,
    ignoresArmour:       def.ignoresArmour       ?? false,
    mortarMode:    false,
    mortarTargetX: null,
    mortarTargetY: null,
    mortarVolley:  1,
  };
}
